[connections.supabase]
SUPABASE_URL = "https://lxfpebxnepvprrnehnzl.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4ZnBlYnhuZXB2cHJybmVobnpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzAxMjk4MTAsImV4cCI6MjA0NTcwNTgxMH0.71_1IXjjCXmH5B7jrZfCW0gzTucjIyHKZxLcTtbT0f4"